extends RefCounted
class_name Enums

# Camera & Visual Enums
#enum CAM_MOVE_STATE {DRAG, ZOOM, SCROLL}
enum FADE_STATE {IN, PAUSE, OUT}
enum CANVAS_EFFECT {VIGNETTE, CHROMATIC_ABB, RAIN}

#Gameplay Enums
#enum GEAR {REVERSE, FIRST, SECOND, THIRD, FOURTH}
enum CONTROL_TYPE {PLAYER, AI, NONE, SCRIPT}
